### ISSUE TITLE
[1.13.2] Crash on Server Load

### ISSUE THREAD

**Issue by Morpheus1101** [ichttt/McPaint#5] opened 2019-02-15 22:19 UTC
Not sure if this is meant to be clientside only, howevber when loading on a server it crashes with...
[crash-2019-02-16_08.14.23-server.txt](https://github.com/ichttt/McPaint/files/2871067/crash-2019-02-16_08.14.23-server.txt)

**Comment by ichttt** [comment] 2019-02-15 22:25
Can you give me a full log? Seems like fml fails to output a valid crash report

**Comment by Morpheus1101** [comment] 2019-02-15 22:28
[debug.log](https://github.com/ichttt/McPaint/files/2871086/debug.log)
[latest.log](https://github.com/ichttt/McPaint/files/2871087/latest.log)

**Comment by ichttt** [comment] 2019-02-15 22:44
Really weird, lthis crash make no sense at all. However, if I try dedicated server in my dev enviroment, the error is much more clear... Will fix the error I see in dev and hope that it fixes this

**Comment by ichttt** [comment] 2019-02-15 22:59
Fixed in 1.3.1. Should be on CF soon

**Comment by Morpheus1101** [comment] 2019-02-15 23:12
Unfortauntely its still crashing

**Comment by Morpheus1101** [comment] 2019-02-15 23:13
Server Side issue [crash-2019-02-16_09.11.04-server.txt](https://github.com/ichttt/McPaint/files/2871195/crash-2019-02-16_09.11.04-server.txt)

Client Side issue
[latest.log](https://github.com/ichttt/McPaint/files/2871210/latest.log)
https://puu.sh/CMOTj/b4093e6c57.png

**Comment by ichttt** [comment] 2019-02-15 23:29
Tbh I think it's a forge issue. Will take a look later

**Comment by Morpheus1101** [comment] 2019-02-15 23:32
Its highly possible being the other problematic mods ive encountered so far, it is beta, so im not overly surprised.

**Comment by ichttt** [comment] 2019-02-16 00:05
Sorry, not able to reproduce this. Please try again with only mcpaint in your mods folder and the forge version 25.0.10 (latest)

**Comment by Morpheus1101** [comment] 2019-02-16 00:15
Ok, seems on its own it works aok, so it would seem there is some sort of other mod interaction occurring causing it to error, i'll have to do some testing and see which mod is causing it.

**Comment by Morpheus1101** [comment] 2019-02-20 01:51
Update: I've gone through my mods list untill it broke, removed mods i added, re-added 1 by 1 an everything works fine...rinse an repeate process, exact same response...so at this stage my end result is I QUIT .. this is the 4th mod ive tried to track down an issue with the exact same result, so im out of ideas to what is going on.

**Comment by Morpheus1101** [comment] 2019-03-21 09:23
Ok, so attempting a re-visit on this issue being a lot of time has passed and more updates with forge, Log file gives more information more targeted at MCPaint then previously....

Loading Client Side Gives [THIS PIC](https://puu.sh/D39Gl/35e94af4c4.png)

Latest Log @ https://pastebin.com/W3yfeKjd

**Comment by ichttt** [comment] 2019-03-21 09:29
It seems like EventBus is currently not thread safe. There is a open pull request to fix this on forge's side, though. I will double check if there are any other operations that are not thread safe and need to be synced.

**Comment by Morpheus1101** [comment] 2019-03-22 12:14
Something i have been told as ive had a few mods error in a similar fashion, is that the Forge Eventbus isnt threadsafe, there is a PR for a patch submitted to fix this on forge side.

**Comment by ichttt** [comment] 2019-03-22 12:37
That's what I said...

**Comment by Morpheus1101** [comment] 2019-03-22 12:38
rofl, woops, meant to paste this on another tracker for another mod that had a similar problem

**Comment by ichttt** [comment] 2019-03-26 11:22
Should be fixed with latest forge

**Closed as completed by ichttt** 2019-03-26 11:22 UTC
